"""Add Tryout model with deadline

Revision ID: 6372a2b2d8a8
Revises: eb583ac4e943
Create Date: 2024-11-11 17:00:58.400061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6372a2b2d8a8'
down_revision = 'eb583ac4e943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
