"""Update unique_id generation

Revision ID: eb583ac4e943
Revises: 3df529be9edc
Create Date: 2024-11-11 15:14:53.189031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb583ac4e943'
down_revision = '3df529be9edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###
